name: HEAD of dependencies

on:
  push:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:

jobs:
  scipy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install distribution build requiements
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc python3-dev libopenblas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache swig libmpc-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip --no-cache-dir --quiet install --upgrade --editable .[test]
        python -m pip uninstall --yes scipy
        python -m pip install --upgrade cython pybind11
        python -m pip install --upgrade mpmath gmpy2 pythran
        python -m pip install --upgrade meson
        python -m pip list

    - name: Build SciPy
      run: |
        git clone --recurse-submodules -j8 https://github.com/scipy/scipy.git
        cd scipy
        export NPY_NUM_BUILD_JOBS=2
        python -u runtests.py --parallel 4 --build-only
        python -m pip install --upgrade .
        cd ..

    - name: List installed Python libraries
      run: |
        python -m pip list

    - name: Test with pytest
      run: |
        python -m pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.py

  iminuit:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip --no-cache-dir --quiet install --upgrade --editable .[test]
        python -m pip uninstall --yes iminuit
        python -m pip install --upgrade cython
        python -m pip install --upgrade git+git://github.com/scikit-hep/iminuit.git
        python -m pip list
    - name: Test with pytest
      run: |
        python -m pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.py

  uproot3:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip --no-cache-dir --quiet install --upgrade --editable .[test]
        python -m pip uninstall --yes uproot3
        python -m pip install --upgrade git+git://github.com/scikit-hep/uproot3.git
        python -m pip list
    - name: Test with pytest
      run: |
        python -m pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.py

  uproot4:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip --no-cache-dir --quiet install --upgrade --editable .[test]
        python -m pip uninstall --yes uproot
        python -m pip install --upgrade git+git://github.com/scikit-hep/uproot4.git
        python -m pip list
    - name: Test with pytest
      run: |
        python -m pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.py

  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip --no-cache-dir --quiet install --upgrade --editable .[test]
        python -m pip uninstall --yes pytest
        python -m pip install --upgrade git+git://github.com/pytest-dev/pytest.git
        python -m pip list
    - name: Test with pytest
      run: |
        python -m pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.py
